### PR TITLE
458: Markdown linter as a local npm script & Git Action execution 

### PR DESCRIPTION
**Pull request by adigidh**
fixes https://github.com/spiffe/tornjak/issues/458

Summary of Changes: 
- Custom Markdown Linting configuration : `.markdownlint.yml` that holds the rules (can be updated based on our requirements)
- NPM script added to the project to complete markdown linting locally: `markdownlint-cli2` is the CLI tool that helps us with the script execution.
- `npm run lint` will produce results for the markdown linting errors. 
- `npm run lint: fix` will help to auto fix these issues for markdown linting
- Updated Markdown files with corresponding linting fixes
- Markdown Linter named Github Action added to the workflows which does the following: 
           - Uses a custom configuration file
          - Runs markdown linter on markdown files in the `docs` directory
          - `continue-on-error: true` parameter set currently to not fail the github action on every pull request

### CODE REVIEW

**Review by mamy-CS — COMMENTED** [review]
Thank you for this, let's fix some of the lint errors on the pr docs/blogs.md and this should be good to go.

**Comment by adigidh** [comment]
> Thank you for this, let's fix some of the lint errors on the pr docs/blogs.md and this should be good to go.

Thanks for taking a look @mamy-CS.
Made the corresponding updates. Changed some yaml rules to avoid noise in the resulting markdown files.

**Comment by mamy-CS** [comment]
@adigidh we have a building failure in the frontend please check. https://github.com/spiffe/tornjak/actions/runs/11113268459/job/30918941927?pr=503

**Comment by mamy-CS** [comment]
@adigidh try the following steps to fix the npm authentication error:
- Delete the `package-lock.json` file 
- Delete your local `node_modules` folder
- Upgrade the node version to the latest
- Update npm as well
- Run `npm install`

**Comment by adigidh** [comment]
@mamy-CS : 
Looks like the project required node 18 and above, I'm already on the recent node versions..

```
node - v

v22.2.0

npm -v

10.7.0
```

I think I figured out the issue. Because the project by itself doesn't have a `.npmrc` file at the root of the frontend folder, when I do a npm install it tries to use the creds in my global `~/.npmrc` file. Thereby the authentication issues as it tried to look to download these packages from internal artifactory. This can be solved by adding a `.npmrc`. Will make these changes and push shortly

**Review by mamy-CS — APPROVED** [review]
Thank you for the pr @adigidh 
/lgtm

**Pull request merged**
